import { replaceSpacesWithDashes } from "@/app/lib/utils";

export const HOLDING_INVESTMENT_RETURN_ITEM_NAME = "Holding Investment Return";
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = HOLDING_INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${HOLDING_INVESTMENT_RETURN_ITEM_NAME}s`;
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(HOLDING_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);

export const MANUAL_INVESTMENT_RETURN_ITEM_NAME = "Manual Investment Return";
export const MANUAL_INVESTMENT_ITEM_NAME = "Manual Investment";
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = MANUAL_INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${MANUAL_INVESTMENT_RETURN_ITEM_NAME}s`;
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(MANUAL_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);

export const INVESTMENT_RETURN_ITEM_NAME = "Investment Return";
export const INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${INVESTMENT_RETURN_ITEM_NAME}s`;
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);
