import { replaceSpacesWithDashes } from "@/app/lib/utils";

export const CASHFLOW_ITEM_NAME = "Cashflow";
export const CASHFLOW_ITEM_NAME_LOWERCASE = CASHFLOW_ITEM_NAME.toLowerCase();

export const EXPENSE_ITEM_NAME = "Expense";
export const EXPENSE_ITEM_NAME_PLURAL = `${EXPENSE_ITEM_NAME}s`;
export const EXPENSE_ITEM_NAME_LOWERCASE = EXPENSE_ITEM_NAME.toLowerCase();
export const EXPENSE_ITEM_NAME_LOWERCASE_PLURAL = EXPENSE_ITEM_NAME_PLURAL.toLowerCase();

export const INCOME_ITEM_NAME = "Income";
export const INCOME_ITEM_NAME_LOWERCASE = INCOME_ITEM_NAME.toLowerCase();

export const RECURRENCE_ITEM_NAME = "Recurring";
export const RECURRENCE_ITEM_NAME_LOWERCASE = RECURRENCE_ITEM_NAME.toLowerCase();

export const SUMMARY_ITEM_NAME = "Summary";
export const SUMMARY_ITEM_NAME_LOWERCASE = SUMMARY_ITEM_NAME.toLowerCase();

export const BUDGET_ITEM_NAME = "Budget";
export const BUDGET_ITEM_NAME_LOWERCASE = BUDGET_ITEM_NAME.toLowerCase();

export const HOLDING_SNAPSHOT_ITEM_NAME = "Holding Snapshot";
export const HOLDING_SNAPSHOT_ITEM_NAME_PLURAL = `${HOLDING_SNAPSHOT_ITEM_NAME}s`;
export const HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE = HOLDING_SNAPSHOT_ITEM_NAME.toLowerCase();
export const HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE_PLURAL = `${HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE}s`;
export const HOLDING_SNAPSHOT_ITEM_NAME_LINK = HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE_PLURAL.replace(" ", "-");
export const HOLDING_SNAPSHOT_ITEM_NAME_FORM_ID = HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE.replace(" ", "-");

export const ASSET_ITEM_NAME = "Asset";
export const ASSET_ITEM_NAME_LOWERCASE = ASSET_ITEM_NAME.toLowerCase();
export const ASSET_ITEM_NAME_PLURAL = `${ASSET_ITEM_NAME}s`;
export const ASSET_ITEM_NAME_PLURAL_LOWERCASE = ASSET_ITEM_NAME_PLURAL.toLowerCase();
export const DEBT_ITEM_NAME = "Debt";
export const DEBT_ITEM_NAME_LOWERCASE = DEBT_ITEM_NAME.toLowerCase();
export const DEBT_ITEM_NAME_PLURAL = `${DEBT_ITEM_NAME}s`;
export const DEBT_ITEM_NAME_PLURAL_LOWERCASE = DEBT_ITEM_NAME_PLURAL.toLowerCase();

export const NET_WORTH_ITEM_NAME = "Net Worth";
export const NET_WORTH_ITEM_NAME_LINK = replaceSpacesWithDashes(NET_WORTH_ITEM_NAME.toLowerCase());

export const HOLDING_INVESTMENT_RETURN_ITEM_NAME = "Holding Investment Return";
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = HOLDING_INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${HOLDING_INVESTMENT_RETURN_ITEM_NAME}s`;
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(HOLDING_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const HOLDING_INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(HOLDING_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);

export const MANUAL_INVESTMENT_ITEM_NAME = "Manual Investment";
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME = `${MANUAL_INVESTMENT_ITEM_NAME} Return`;
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = MANUAL_INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${MANUAL_INVESTMENT_RETURN_ITEM_NAME}s`;
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(MANUAL_INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const MANUAL_INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(MANUAL_INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);

export const INVESTMENT_RETURN_ITEM_NAME = "Investment Return";
export const INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${INVESTMENT_RETURN_ITEM_NAME}s`;
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = replaceSpacesWithDashes(INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE);
export const INVESTMENT_RETURN_ITEM_NAME_FORM_ID = replaceSpacesWithDashes(INVESTMENT_RETURN_ITEM_NAME_LOWERCASE);

export const DASHBOARDS_ITEM_NAME = "Dashboards";
export const DASHBOARDS_ITEM_NAME_LOWERCASE = DASHBOARDS_ITEM_NAME.toLowerCase();
