export const INVESTMENT_RETURN_ITEM_NAME = "Investment Return";
export const INVESTMENT_RETURN_ITEM_NAME_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL = `${INVESTMENT_RETURN_ITEM_NAME}s`;
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE = INVESTMENT_RETURN_ITEM_NAME_PLURAL.toLowerCase();
export const INVESTMENT_RETURN_ITEM_NAME_PLURAL_LINK = INVESTMENT_RETURN_ITEM_NAME_PLURAL_LOWERCASE.replace(" ", "-");
export const INVESTMENT_RETURN_ITEM_NAME_FORM_ID = INVESTMENT_RETURN_ITEM_NAME_LOWERCASE.replace(" ", "-");
export const MANUAL_INVESTMENT_ITEM_NAME = "Manual Investment";