export const HOLDING_SNAPSHOT_ITEM_NAME = "Holding Snapshot";
export const HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE = HOLDING_SNAPSHOT_ITEM_NAME.toLowerCase();
export const HOLDING_SNAPSHOT_ITEM_NAME_FORM_ID = HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE.replace(" ", "-");