export const HOLDING_SNAPSHOT_ITEM_NAME = "Holding Snapshot";
export const HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE = HOLDING_SNAPSHOT_ITEM_NAME.toLowerCase();
export const HOLDING_SNAPSHOT_ITEM_NAME_FORM_ID = HOLDING_SNAPSHOT_ITEM_NAME_LOWERCASE.replace(" ", "-");
export const NET_WORTH_ITEM_NAME = "Net Worth";
export const NET_WORTH_ITEM_NAME_LOWERCASE = NET_WORTH_ITEM_NAME.toLowerCase();
export const NET_WORTH_ITEM_NAME_LINK = NET_WORTH_ITEM_NAME_LOWERCASE.replace(" ", "-");